name: Update uBlacklist subscription weekly

on:
  schedule:
    - cron: "0 16 * * 1"
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '>=1.17.0'
        cache: false

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 1
        submodules: true

    - name: Compile subscription
      run: |
        git submodule update --init --remote --force source/eallion/uBlacklist-Subscription source/obgnail/chinese-internet-is-dead
        cat source/eallion/uBlacklist-Subscription/ublacklist.txt source/obgnail/chinese-internet-is-dead/blocklist.txt > tools/uBlacklist.txt
        cd tools
        go run . -input uBlacklist.txt -output uBlacklist.txt -backup uBlacklist_backup.txt -exclusions ../exclusions.txt
        mv uBlacklist.txt ../uBlacklist.txt
        cd ..

        # 获取当前时间存入环境变量（用于提交信息）
        echo "CURRENT_TIME=$(TZ=UTC-8 date +'%Y-%m-%d %T %z')" >> $GITHUB_ENV

    - name: Commit files
      uses: EndBug/add-and-commit@v11
      with:
        message: "ci(build): update weekly at ${{ env.CURRENT_TIME }}"
        committer_name: 'github-actions[bot]'
        committer_email: 'github-actions[bot]@users.noreply.github.com'
        add: |
          'uBlacklist.txt'
          'tools/uBlacklist_backup.txt'
